{% set name = "applaunchservices" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cc6ad5c6c88457230b3cc3d1f76c39c00dcd2597af9c6ee592dce5e67eb2cad

build:
  skip: true  # [not osx]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyobjc-framework-coreservices

test:
  imports:
    - applaunchservices
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/impact27/applaunchservices
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple package for registering an app with apple Launch Services to handle UTI and URL
  dev_url: https://github.com/impact27/applaunchservices

extra:
  recipe-maintainers:
    - impact27
    - goanpeca
